"""
Multilingual Keyword System
===========================
Works BOTH directions:
1. User types in English → expands to all languages for that country
2. User types in ANY language → auto-detects and maps to correct business type

Covers 12 languages, 40+ business types, 80+ countries.
"""

import difflib
from typing import List, Tuple, Optional


# =============================================================================
# FORWARD MAP: English business type → translations in all languages
# =============================================================================
BUSINESS_TYPES = {
    "pharmacy": {
        "osm_amenity": "pharmacy",
        "osm_shop": "chemist",
        "en": ["pharmacy", "drugstore", "apothecary", "chemist"],
        "fr": ["pharmacie", "officine"],
        "ar": ["صيدلية", "صيدلي", "drugstore"],
        "ja": ["薬局", "薬店", "ドラッグストア", "調剤薬局"],
        "es": ["farmacia", "droguería", "parafarmacia"],
        "de": ["apotheke", "drogerie"],
        "pt": ["farmácia", "drogaria"],
        "it": ["farmacia", "parafarmacia"],
        "tr": ["eczane"],
        "ru": ["аптека", "фармация"],
        "zh": ["药店", "药房", "大药房"],
        "ko": ["약국"],
    },
    "dentist": {
        "osm_amenity": "dentist",
        "osm_healthcare": "dentist",
        "en": ["dentist", "dental clinic", "dental office", "dental care"],
        "fr": ["dentiste", "cabinet dentaire", "clinique dentaire", "centre dentaire"],
        "ar": ["طبيب أسنان", "عيادة أسنان", "مستشفى أسنان", "-clinic dentaire"],
        "ja": ["歯科", "歯科医院", "歯医者", "デンタルクリニック", "歯科診療所"],
        "es": ["dentista", "clínica dental", "consultorio dental"],
        "de": ["zahnarzt", "zahnklinik", "zahnpraxis", "dentalpraxis"],
        "pt": ["dentista", "clínica odontológica", "consultório odontológico"],
        "it": ["dentista", "studio dentistico", "clinica dentistica"],
        "tr": ["diş hekimi", "diş kliniği", "diş polikliniği"],
        "ru": ["стоматолог", "стоматология", "зубной врач"],
        "zh": ["牙科", "牙科诊所", "口腔医院", "牙医"],
        "ko": ["치과", "치과 의원", "치과병원"],
    },
    "restaurant": {
        "osm_amenity": "restaurant",
        "en": ["restaurant", "eatery", "dining", "bistro", "grill"],
        "fr": ["restaurant", "brasserie", "bistrot", "grill", "troquet"],
        "ar": ["مطعم", "مطبخ", "وجبات"],
        "ja": ["レストラン", "食堂", "飲食店", "グルメ", "ダイニング"],
        "es": ["restaurante", "comedor", "bistró"],
        "de": ["restaurant", "gaststätte", "bistro", "grill"],
        "pt": ["restaurante", "lanchonete", "bistrô"],
        "it": ["ristorante", "trattoria", "osteria", "birreria"],
        "tr": ["restoran", "lokanta", "yemek salonu"],
        "ru": ["ресторан", "кафе", "столовая"],
        "zh": ["餐厅", "饭店", "餐馆", "酒楼"],
        "ko": ["식당", "음식점", "레스토랑"],
    },
    "hotel": {
        "osm_amenity": "hotel",
        "osm_tourism": "hotel",
        "en": ["hotel", "motel", "inn", "lodge", "resort", "hostel"],
        "fr": ["hôtel", "auberge", "gîte", "pension", "riad"],
        "ar": ["فندق", "منتجع", "نُزُل", "إقامة"],
        "ja": ["ホテル", "旅館", "民宿", "ゲストハウス", "リゾート"],
        "es": ["hotel", "hostal", "posada", "alojamiento", "resort"],
        "de": ["hotel", "pension", "gasthof", "herberge", "resort"],
        "pt": ["hotel", "pousada", "hostel", "resort"],
        "it": ["hotel", "albergo", "pensione", "ostello", "resort"],
        "tr": ["otel", "konaklama", "pansiyon", "motel"],
        "ru": ["отель", "гостиница", "хостел", "мини-отель"],
        "zh": ["酒店", "宾馆", "旅馆", "民宿", "度假村"],
        "ko": ["호텔", "여관", "게스트하우스", "리조트"],
    },
    "cafe": {
        "osm_amenity": "cafe",
        "en": ["cafe", "coffee shop", "coffeehouse", "cafeteria", "teahouse"],
        "fr": ["café", "salon de thé", "coffee shop"],
        "ar": ["مقهى", "قهوة", "كافيه"],
        "ja": ["カフェ", "喫茶店", "コーヒーショップ", "茶屋"],
        "es": ["café", "cafetería", "coffee shop"],
        "de": ["café", "kaffeehaus", "kaffee"],
        "pt": ["café", "cafetería", "lanchonete"],
        "it": ["café", "bar", "caffetteria"],
        "tr": ["kahve", "kahvehane", "kafe"],
        "ru": ["кафе", "кофейня", "каве"],
        "zh": ["咖啡馆", "咖啡厅", "茶馆"],
        "ko": ["카페", "커피숍", "다방"],
    },
    "bar": {
        "osm_amenity": "bar",
        "en": ["bar", "pub", "tavern", "lounge", "nightclub"],
        "fr": ["bar", "pub", "taverne", "brasserie"],
        "ar": [" bar ", "مقهى ليلي", "نادي ليلي"],
        "ja": ["バー", "パブ", "酒場", "スナック", "クラブ"],
        "es": ["bar", "pub", "taberna", "discoteca"],
        "de": ["bar", "pub", "kneipe", "taverne"],
        "pt": ["bar", "pub", "taberna"],
        "it": ["bar", "pub", "taverna", "discoteca"],
        "tr": ["bar", "pub", "mekan"],
        "ru": ["бар", "паб", "таверна"],
        "zh": ["酒吧", "酒馆"],
        "ko": ["바", "술집", "펍"],
    },
    "gym": {
        "osm_amenity": "gym",
        "osm_leisure": "fitness_centre",
        "en": ["gym", "fitness center", "fitness club", "workout"],
        "fr": ["salle de sport", "gym", "centre de fitness", "studio de remise en forme"],
        "ar": ["صالة رياضية", "جيم", "نادي رياضي"],
        "ja": ["ジム", "フィットネス", "体育館", "スポーツジム"],
        "es": ["gimnasio", "centro de fitness", "sala de deportes"],
        "de": ["fitnessstudio", "fitnesscenter", "gym"],
        "pt": ["academia", "ginástica", "centro de fitness"],
        "it": ["palestra", "centro fitness", "gym"],
        "tr": ["spor salonu", "fitness salonu", "jimnastik"],
        "ru": ["спортзал", "фитнес-клуб", "тренажёрный зал"],
        "zh": ["健身房", "健身中心", "体育中心"],
        "ko": ["헬스장", "체육관", "피트니스센터"],
    },
    "hairdresser": {
        "osm_amenity": "hairdresser",
        "osm_shop": "beauty",
        "en": ["hairdresser", "hair salon", "barber", "barbershop"],
        "fr": ["coiffeur", "salon de coiffure", "barbier"],
        "ar": ["حلاق", "صالون حلاقة", "مشغل"],
        "ja": ["美容院", "理容院", "ヘアサロン", "美容室"],
        "es": ["peluquería", "salón de belleza", "barbería"],
        "de": ["friseur", "haarstudio", "barbershop"],
        "pt": ["cabeleireiro", "salão de beleza", "barbearia"],
        "it": ["parrucchiere", "salone di bellezza", "barberia"],
        "tr": ["kuaför", "berber", "güzellik salonu"],
        "ru": ["парикмахерская", "салон красоты", "барбершоп"],
        "zh": ["理发店", "美发店", "发型屋"],
        "ko": ["미용실", "이발소", "헤어숍"],
    },
    "bakery": {
        "osm_amenity": "bakery",
        "osm_shop": "bakery",
        "en": ["bakery", "bakeshop", "pastry shop"],
        "fr": ["boulangerie", "pâtisserie"],
        "ar": ["مخبزة", "خبازية"],
        "ja": ["パン屋", "ベーカリー", "製パン店"],
        "es": ["panadería", "pastelería"],
        "de": ["bäckerei", "konditorei", "kuchenladen"],
        "pt": ["padaria", "confeitaria"],
        "it": ["forno", "pasticceria", "panificio"],
        "tr": ["fırın", "pastane", "ekmekçi"],
        "ru": ["пекарня", "кондитерская"],
        "zh": ["面包店", "糕点店", "烘焙坊"],
        "ko": ["제과점", "빵집"],
    },
    "supermarket": {
        "osm_amenity": "supermarket",
        "osm_shop": "supermarket",
        "en": ["supermarket", "grocery store", "grocery", "food store"],
        "fr": ["supermarché", "épicerie", "hypermarché"],
        "ar": ["سوبر ماركت", "متجر", "بقالة"],
        "ja": ["スーパー", "食品店", "食料品店", "マルエツ"],
        "es": ["supermercado", "tienda de comestibles", "alimentación"],
        "de": ["supermarkt", "lebensmittelgeschäft", "markt"],
        "pt": ["supermercado", "mercearia", "armazém"],
        "it": ["supermercato", "alimentari", "mercato"],
        "tr": ["süpermarket", "bakkal", "market"],
        "ru": ["супермаркет", "продуктовый магазин"],
        "zh": ["超市", "杂货店", "便利店"],
        "ko": ["슈퍼마켓", "마트", "편의점"],
    },
    "doctor": {
        "osm_amenity": "doctors",
        "osm_healthcare": "doctor",
        "en": ["doctor", "clinic", "medical center", "physician"],
        "fr": ["médecin", "cabinet médical", "clinique", "centre médical"],
        "ar": ["طبيب", "عيادة", "مركز طبي", "مستشفى"],
        "ja": ["医院", "診療所", "クリニック", "医者"],
        "es": ["médico", "clínica", "consultorio médico"],
        "de": ["arzt", "praxis", "klinik", "ärztehaus"],
        "pt": ["médico", "clínica", "consultório médico"],
        "it": ["medico", "clinica", "studio medico"],
        "tr": ["doktor", "klinik", "tıp merkezi"],
        "ru": ["врач", "клиника", "медицинский центр"],
        "zh": ["医院", "诊所", "医疗中心"],
        "ko": ["병원", "의원", "의료센터"],
    },
    "hospital": {
        "osm_amenity": "hospital",
        "osm_healthcare": "hospital",
        "en": ["hospital", "medical center", "health center"],
        "fr": ["hôpital", "centre hospitalier", "clinique"],
        "ar": ["مستشفى", "مركز طبي"],
        "ja": ["病院", "医療センター"],
        "es": ["hospital", "centro médico"],
        "de": ["krankenhaus", "klinikum", "klinik"],
        "pt": ["hospital", "centro médico"],
        "it": ["ospedale", "centro medico"],
        "tr": ["hastane", "tıp merkezi"],
        "ru": ["больница", "медицинский центр"],
        "zh": ["医院", "医疗中心"],
        "ko": ["병원", "의료센터"],
    },
    "school": {
        "osm_amenity": "school",
        "en": ["school", "academy", "educational institution"],
        "fr": ["école", "académie", "institution éducative"],
        "ar": ["مدرسة", "أكاديمية"],
        "ja": ["学校", "学園", "学院"],
        "es": ["escuela", "academia", "colegio"],
        "de": ["schule", "akademie", "bildungsinstitut"],
        "pt": ["escola", "academia"],
        "it": ["scuola", "accademia"],
        "tr": ["okul", "akademi"],
        "ru": ["школа", "академия"],
        "zh": ["学校", "学院", "培训机构"],
        "ko": ["학교", "학원", "교육기관"],
    },
    "bank": {
        "osm_amenity": "bank",
        "en": ["bank", "financial institution", "credit union"],
        "fr": ["banque", "institution financière"],
        "ar": ["بنك", "مؤسسة مالية"],
        "ja": ["銀行", "金融機関"],
        "es": ["banco", "institución financiera"],
        "de": ["bank", "kreditinstitut"],
        "pt": ["banco", "instituição financeira"],
        "it": ["banca", "istituto finanziario"],
        "tr": ["banka", "finans kurumu"],
        "ru": ["банк", "финансовое учреждение"],
        "zh": ["银行", "金融机构"],
        "ko": ["은행", "금융기관"],
    },
    "car_repair": {
        "osm_amenity": "car_repair",
        "osm_shop": "car_repair",
        "en": ["car repair", "auto repair", "mechanic", "garage"],
        "fr": ["garage", "réparation auto", "mécanicien"],
        "ar": ["ورشة سيارات", "ميكانيكي", "تصليح سيارات"],
        "ja": ["自動車修理", "カークリニック", "修理工場", "車検"],
        "es": ["taller mecánico", "reparación de coches", "mecánico"],
        "de": ["autowerkstatt", "kfz-werkstatt", "mechaniker"],
        "pt": ["oficina mecânica", "reparação de carros"],
        "it": ["officina meccanica", "autofficina"],
        "tr": ["oto tamir", "otomobil servisi", "mekanik"],
        "ru": ["автомастерская", "ремонт авто", "автосервис"],
        "zh": ["汽车修理", "修车厂", "汽修店"],
        "ko": ["자동차정비", "카센터", "정비소"],
    },
    "lawyer": {
        "osm_amenity": "lawyer",
        "osm_office": "lawyer",
        "en": ["lawyer", "attorney", "law firm", "legal office"],
        "fr": ["avocat", "cabinet d'avocat", "étude notariale"],
        "ar": ["محامي", "مكتب محاماة", "استشاري قانوني"],
        "ja": ["弁護士", "法律事務所", "司法書士"],
        "es": ["abogado", "despacho de abogados", "bufete"],
        "de": ["anwalt", "rechtsanwalt", "kanzlei"],
        "pt": ["advogado", "escritório de advocacia"],
        "it": ["avvocato", "studio legale"],
        "tr": ["avukat", "hukuk bürosu"],
        "ru": ["адвокат", "юрист", "юридическая фирма"],
        "zh": ["律师", "律师事务所", "法律事务所"],
        "ko": ["변호사", "법무사", "법률사무소"],
    },
    "accountant": {
        "osm_amenity": "accountant",
        "osm_office": "accountant",
        "en": ["accountant", "accounting firm", "tax office"],
        "fr": ["comptable", "cabinet comptable", "expert-comptable"],
        "ar": ["محاسب", "مكتب محاسبة"],
        "ja": ["会計士", "税理士", "会計事務所"],
        "es": ["contador", "despacho contable"],
        "de": ["steuerberater", "buchhalter", "rechtsanwaltskanzlei"],
        "pt": ["contador", "escritório contábil"],
        "it": ["commercialista", "studio contabile"],
        "tr": ["muhasebeci", "muhasebe bürosu"],
        "ru": ["бухгалтер", "бухгалтерская фирма"],
        "zh": ["会计师", "会计事务所"],
        "ko": ["회계사", "세무사"],
    },
    "real_estate": {
        "osm_amenity": "estate_agent",
        "osm_office": "estate_agent",
        "en": ["real estate", "real estate agent", "property"],
        "fr": ["immobilier", "agent immobilier", "agence immobilière"],
        "ar": ["عقارات", "سمسار عقارات", "وكيل عقارات"],
        "ja": ["不動産", "不動産会社", "不動産屋"],
        "es": ["inmobiliaria", "agente inmobiliario"],
        "de": ["immobilien", "immobilienmakler", "grundstück"],
        "pt": ["imobiliária", "corretor de imóveis"],
        "it": ["immobiliare", "agente immobiliare"],
        "tr": ["emlak", "emlakçı"],
        "ru": ["недвижимость", "риэлтор", "агентство недвижимости"],
        "zh": ["房地产", "房产中介", "不动产"],
        "ko": ["부동산", "공인중개사"],
    },
    "plumber": {
        "osm_amenity": "plumber",
        "osm_craft": "plumber",
        "en": ["plumber", "plumbing", "pipe fitter"],
        "fr": ["plombier", "installation sanitaire"],
        "ar": ["سباك", " Plumbing"],
        "ja": ["配管工", "水道工", "配管業者"],
        "es": ["fontanero", "plomero"],
        "de": ["klempner", "sanitär"],
        "pt": ["encanador", "hidráulica"],
        "it": ["idraulico", "fontaniere"],
        "tr": ["tesisatçı", "su tesisatı"],
        "ru": ["сантехник", "водопроводчик"],
        "zh": ["水管工", "管道工"],
        "ko": ["배관공", "설비"],
    },
    "electrician": {
        "osm_amenity": "electrician",
        "osm_craft": "electrician",
        "en": ["electrician", "electrical contractor"],
        "fr": ["électricien", "installation électrique"],
        "ar": ["كهربائي", "مقاول كهرباء"],
        "ja": ["電気工事士", "電気技師"],
        "es": ["electricista", "contratista eléctrico"],
        "de": ["elektriker", "elektroinstallateur"],
        "pt": ["eletricista", "instalação elétrica"],
        "it": ["elettricista"],
        "tr": ["elektrikçi", "elektrik tesisatı"],
        "ru": ["электрик", "электромонтёр"],
        "zh": ["电工", "电气工程师"],
        "ko": ["전기공", "전기기술자"],
    },
    "spa": {
        "osm_amenity": "spa",
        "osm_shop": "beauty",
        "en": ["spa", "wellness center", "massage"],
        "fr": ["spa", "centre de bien-être", "massage"],
        "ar": ["سبا", "مركز عافية", "تدليك"],
        "ja": ["スパ", "マッサージ", "リラクゼーション"],
        "es": ["spa", "centro de bienestar", "masaje"],
        "de": ["spa", "wellness", "massage"],
        "pt": ["spa", "bem-estar", "massagem"],
        "it": ["spa", "benessere", "massaggio"],
        "tr": ["spa", "wellness", "masaj"],
        "ru": ["спа", "массаж", "центр здоровья"],
        "zh": ["水疗", "按摩", "养生馆"],
        "ko": ["스파", "마사지", "웰니스센터"],
    },
    "travel_agency": {
        "osm_amenity": "travel_agent",
        "en": ["travel agency", "travel agent", "tour operator"],
        "fr": ["agence de voyage", "tour operator"],
        "ar": ["وكالة سفر", "شركة سياحة"],
        "ja": ["旅行会社", "旅行代理店", "ツアー"],
        "es": ["agencia de viajes", "operador turístico"],
        "de": ["reisebüro", "reiseagentur"],
        "pt": ["agência de viagens", "operadora de turismo"],
        "it": ["agenzia di viaggio", "tour operator"],
        "tr": ["seyahat acentesi", "tur operatörü"],
        "ru": ["турагентство", "турфирма"],
        "zh": ["旅行社", "旅游公司"],
        "ko": ["여행사", "여행사"],
    },
    "vet": {
        "osm_amenity": "veterinary",
        "en": ["veterinary", "vet", "animal hospital"],
        "fr": ["vétérinaire", "clinique vétérinaire"],
        "ar": ["طبيب بيطري", "عيادة بيطري"],
        "ja": ["動物病院", "獣医", "ペット病院"],
        "es": ["veterinario", "clínica veterinaria"],
        "de": ["tierarzt", "tierklinik"],
        "pt": ["veterinário", "clínica veterinária"],
        "it": ["veterinario", "clinica veterinaria"],
        "tr": ["veteriner", "veteriner kliniği"],
        "ru": ["ветеринар", "ветеринарная клиника"],
        "zh": ["兽医", "宠物医院"],
        "ko": ["수의사", "동물병원"],
    },
    "optician": {
        "osm_amenity": "optician",
        "osm_shop": "optician",
        "en": ["optician", "optical", "eye care"],
        "fr": ["opticien", "lunetterie", "centre ophtalmologique"],
        "ar": ["نظاراتي", "مركز العيون"],
        "ja": ["眼鏡店", "オプティシャン", "眼科"],
        "es": ["óptico", "óptica", "centro oftalmológico"],
        "de": ["optiker", "optik", "augenklinik"],
        "pt": ["óptica", "óptico"],
        "it": ["ottico", "ottica"],
        "tr": ["gözlükçü", "optik"],
        "ru": ["оптик", "оптика"],
        "zh": ["眼镜店", "眼科"],
        "ko": ["안경점", "안과"],
    },
    "jewelry": {
        "osm_amenity": "jewelry",
        "osm_shop": "jewelry",
        "en": ["jewelry", "jeweler", "jewellery store"],
        "fr": ["bijouterie", "joaillier", "joaillerie"],
        "ar": ["مجوهرات", "مجوهراتي"],
        "ja": ["宝石店", "ジュエリーショップ"],
        "es": ["joyería", "joyero"],
        "de": ["juwelier", "schmuckgeschäft"],
        "pt": ["joalheria", "joalheiro"],
        "it": ["gioielleria", "gioielliere"],
        "tr": ["kuyumcu", "kuyumcu dükkanı"],
        "ru": ["ювелирный магазин", "ювелир"],
        "zh": ["珠宝店", "珠宝行"],
        "ko": ["보석점", "귀금속점"],
    },
    "furniture": {
        "osm_amenity": "furniture",
        "osm_shop": "furniture",
        "en": ["furniture", "furniture store", "home furnishing"],
        "fr": ["meubles", "magasin de meubles", "décoration intérieure"],
        "ar": ["أثاث", "محل أثاث"],
        "ja": ["家具店", "インテリアショップ"],
        "es": ["muebles", "tienda de muebles"],
        "de": ["möbel", "möbelladen"],
        "pt": ["móveis", "loja de móveis"],
        "it": ["mobili", "negozio di mobili"],
        "tr": ["mobilya", "mobilya mağazası"],
        "ru": ["мебель", "мебельный магазин"],
        "zh": ["家具店", "家具商场"],
        "ko": ["가구점", "인테리어숍"],
    },
    "clothing": {
        "osm_shop": "clothes",
        "osm_shop_alt": "fashion",
        "en": ["clothing", "clothing store", "fashion", "boutique"],
        "fr": ["vêtements", "boutique de mode", "prêt-à-porter"],
        "ar": ["ملابس", "متجر ملابس", "أزياء"],
        "ja": ["衣料品店", "アパレルショップ", "ファッション"],
        "es": ["ropa", "tienda de ropa", "boutique"],
        "de": ["kleidung", "bekleidungsgeschäft", "mode"],
        "pt": ["roupa", "loja de roupas", "moda"],
        "it": ["abbigliamento", "negozio di abbigliamento"],
        "tr": ["giyim", "mağaza", "butik"],
        "ru": ["одежда", "магазин одежды"],
        "zh": ["服装店", "时装店"],
        "ko": ["의류점", "패션숍"],
    },
    "electronics": {
        "osm_shop": "electronics",
        "en": ["electronics", "electronics store", "appliance store"],
        "fr": ["électronique", "magasin d'électronique"],
        "ar": ["إلكترونيات", "متجر إلكترونيات"],
        "ja": ["家電量販店", "電器店", "エレクトロニクス"],
        "es": ["electrónica", "tienda de electrónica"],
        "de": ["elektronik", "elektronikgeschäft"],
        "pt": ["eletrônicos", "loja de eletrônicos"],
        "it": ["elettronica", "negozio di elettronica"],
        "tr": ["elektronik", "elektronik mağazası"],
        "ru": ["электроника", "магазин электроники"],
        "zh": ["电子产品", "电器店"],
        "ko": ["전자제품", "가전제품점"],
    },
    "hardware": {
        "osm_shop": "hardware",
        "en": ["hardware", "hardware store", "diy store"],
        "fr": ["quincaillerie", "magasin de bricolage"],
        "ar": ["عدد", "متجر أدوات"],
        "ja": ["五金店", "ホームセンター", "工具店"],
        "es": ["ferretería", "tienda de bricolaje"],
        "de": ["eisenwaren", "baumarkt", "hardware"],
        "pt": ["ferragens", "loja de ferragens"],
        "it": ["ferramenta", "negozio di ferramenta"],
        "tr": ["hırdavat", "yapı market"],
        "ru": ["хозяйственный магазин", "строительные материалы"],
        "zh": ["五金店", "建材店"],
        "ko": ["철물점", "하드웨어숍"],
    },
    "florist": {
        "osm_shop": "florist",
        "en": ["florist", "flower shop", "nursery"],
        "fr": ["fleuriste", "magasin de fleurs", "pépinière"],
        "ar": ["محل زهور", "وردي"],
        "ja": ["花屋", "フラワーショップ"],
        "es": ["floristería", "vivero"],
        "de": ["florist", "blumenladen", "gärtnerei"],
        "pt": ["floricultura", "loja de flores"],
        "it": ["fiorista", "negozio di fiori"],
        "tr": ["çiçekçi", "saksı çiçekçisi"],
        "ru": ["цветочный магазин", "флорист"],
        "zh": ["花店", "花圃"],
        "ko": ["화훼점", "꽃집"],
    },
    "bookstore": {
        "osm_shop": "books",
        "en": ["bookstore", "bookshop", "book store"],
        "fr": ["librairie", "magasin de livres"],
        "ar": ["مكتبة", "متجر كتب"],
        "ja": ["書店", "本屋", "ブックストア"],
        "es": ["librería", "tienda de libros"],
        "de": ["buchhandlung", "bookstore"],
        "pt": ["livraria", "loja de livros"],
        "it": ["libreria", "negozio di libri"],
        "tr": ["kitapçı", "kitap dükkanı"],
        "ru": ["книжный магазин", "книжный"],
        "zh": ["书店", "图书店"],
        "ko": ["서점", "서점"],
    },
    "coworking": {
        "osm_amenity": "coworking",
        "en": ["coworking", "coworking space", "shared office"],
        "fr": ["coworking", "espace de coworking"],
        "ar": ["مساحة عمل مشتركة"],
        "ja": ["コワーキング", "シェアオフィス"],
        "es": ["coworking", "espacio de coworking"],
        "de": ["coworking", "coworking-space"],
        "pt": ["coworking", "espaço de coworking"],
        "it": ["coworking", "spazio di coworking"],
        "tr": ["coworking", "çalışma alanı"],
        "ru": ["коворкинг", "коворкинг-центр"],
        "zh": ["联合办公", "共享办公室"],
        "ko": ["코워킹", "공유 오피스"],
    },
    "nursery": {
        "osm_amenity": "kindergarten",
        "en": ["nursery", "kindergarten", "daycare", "preschool"],
        "fr": ["crèche", "maternelle", "garderie"],
        "ar": ["روضة", "حضانة", "مهد أطفال"],
        "ja": ["幼稚園", "保育園", "ナーサリー"],
        "es": ["guardería", "jardín de infantes", "preescolar"],
        "de": ["kindergarten", "kita", "tagesstätte"],
        "pt": ["berçário", "jardim de infância"],
        "it": ["asilo", "scuola materna"],
        "tr": ["kreş", "anaokulu"],
        "ru": ["детский сад", "ясли"],
        "zh": ["幼儿园", "托儿所"],
        "ko": ["어린이집", "유치원"],
    },
    "photographer": {
        "osm_amenity": "photographer",
        "en": ["photographer", "photo studio", "photography"],
        "fr": ["photographe", "studio photo"],
        "ar": ["مصوّر", "ستوديو تصوير"],
        "ja": ["写真館", "フォトスタジオ", "カメラ屋"],
        "es": ["fotógrafo", "estudio de fotografía"],
        "de": ["fotograf", "fotostudio"],
        "pt": ["fotógrafo", "estúdio fotográfico"],
        "it": ["fotografo", "studio fotografico"],
        "tr": ["fotoğrafçı", "fotoğraf stüdyosu"],
        "ru": ["фотограф", "фотостудия"],
        "zh": ["摄影师", "照相馆"],
        "ko": ["사진작가", "스튜디오"],
    },
    "catering": {
        "osm_amenity": "catering",
        "en": ["catering", "caterer", "event catering"],
        "fr": ["traiteur", "service de traiteur"],
        "ar": ["تموين", "خدمة تموين"],
        "ja": ["ケータリング", "配食サービス"],
        "es": ["catering", "servicio de catering"],
        "de": ["catering", "catering-service"],
        "pt": ["catering", "serviço de catering"],
        "it": ["catering", "servizio di catering"],
        "tr": ["catering", "yemek servisi"],
        "ru": ["кейтеринг", "питание на вынос"],
        "zh": ["餐饮服务", "宴会服务"],
        "ko": ["케이터링", "출장음식"],
    },
    "event_hall": {
        "osm_amenity": "events_venue",
        "en": ["event hall", "conference center", "banquet hall"],
        "fr": ["salle des fêtes", "centre de conférence", "salle de réception"],
        "ar": ["قاعة أحداث", "مركز مؤتمرات"],
        "ja": ["イベントホール", "会議室", "パーティー場"],
        "es": ["sala de eventos", "centro de conferencias"],
        "de": ["veranstaltungshalle", "tagungszentrum"],
        "pt": ["salão de eventos", "centro de conferências"],
        "it": ["sala eventi", "centro conferenze"],
        "tr": ["etkinlik salonu", "konferans merkezi"],
        "ru": ["конференц-зал", "выставочный центр"],
        "zh": ["活动大厅", "会议中心"],
        "ko": ["행사홀", "컨벤션센터"],
    },
    "cleaning": {
        "osm_amenity": "cleaning",
        "en": ["cleaning", "cleaning service", "janitorial"],
        "fr": ["nettoyage", "service de nettoyage"],
        "ar": ["تنظيف", "خدمة تنظيف"],
        "ja": ["クリーニング", "清掃業者"],
        "es": ["limpieza", "servicio de limpieza"],
        "de": ["reinigung", "reinigungsdienst"],
        "pt": ["limpeza", "serviço de limpeza"],
        "it": ["pulizia", "servizio di pulizia"],
        "tr": ["temizlik", "temizlik hizmeti"],
        "ru": ["уборка", "клининговая служба"],
        "zh": ["清洁", "保洁服务"],
        "ko": ["청소", "청소업체"],
    },
    "security": {
        "osm_amenity": "security",
        "en": ["security", "security company", "guard service"],
        "fr": ["sécurité", "entreprise de sécurité"],
        "ar": ["أمن", "شركة أمن"],
        "ja": ["警備", "セキュリティ", "警備会社"],
        "es": ["seguridad", "empresa de seguridad"],
        "de": ["sicherheit", "sicherheitsunternehmen"],
        "pt": ["segurança", "empresa de segurança"],
        "it": ["sicurezza", "ditta di sicurezza"],
        "tr": ["güvenlik", "güvenlik şirketi"],
        "ru": ["охрана", "охранные услуги"],
        "zh": ["安保", "保安公司"],
        "ko": ["보안", "경비업체"],
    },
    "post_office": {
        "osm_amenity": "post_office",
        "en": ["post office", "mail service"],
        "fr": ["bureau de poste", "la poste"],
        "ar": ["مكتب بريد"],
        "ja": ["郵便局"],
        "es": ["oficina de correos", "correo"],
        "de": ["post", "postamt"],
        "pt": ["correios", "agência postal"],
        "it": ["ufficio postale", "poste italiane"],
        "tr": ["posta", "posta ofisi"],
        "ru": ["почта", "почтовое отделение"],
        "zh": ["邮局"],
        "ko": ["우체국"],
    },
    "marketing_agency": {
        "osm_office": "company",
        "en": ["marketing agency", "advertising agency", "digital marketing", "marketing firm"],
        "fr": ["agence marketing", "agence publicitaire", "agence digitale"],
        "ar": ["وكالة تسويق", "وكالة إعلانات", "تسويق رقمي"],
        "ja": ["マーケティング会社", "広告代理店", "デジタルマーケティング"],
        "es": ["agencia de marketing", "agencia publicitaria", "marketing digital"],
        "de": ["marketingagentur", "werbeagentur", "digitalagentur"],
        "pt": ["agência de marketing", "agência de publicidade"],
        "it": ["agenzia di marketing", "agenzia pubblicitaria"],
        "tr": ["pazarlama ajansı", "reklam ajansı"],
        "ru": ["маркетинговое агентство", "рекламное агентство"],
        "zh": ["营销公司", "广告公司", "数字营销"],
        "ko": ["마케팅 에이전시", "광고 대행사"],
    },
    "it_company": {
        "osm_office": "company",
        "en": ["IT company", "software company", "tech company", "IT services"],
        "fr": ["société informatique", "entreprise technologique", "société logicielle"],
        "ar": ["شركة تقنية", "شركة برمجيات", "تكنولوجيا"],
        "ja": ["IT企業", "ソフトウェア会社", "テック企業"],
        "es": ["empresa de TI", "empresa de software", "empresa tecnológica"],
        "de": ["IT-Unternehmen", "Softwareunternehmen", "Tech-Unternehmen"],
        "pt": ["empresa de TI", "empresa de software"],
        "it": ["azienda IT", "azienda software"],
        "tr": ["IT şirketi", "yazılım şirketi", "tech şirketi"],
        "ru": ["IT-компания", "компания по разработке ПО"],
        "zh": ["IT公司", "软件公司", "科技公司"],
        "ko": ["IT 회사", "소프트웨어 회사", "테크 회사"],
    },
    "construction_company": {
        "osm_office": "company",
        "en": ["construction company", "builder", "contractor", "construction firm"],
        "fr": ["entreprise de construction", "maçonnerie", "bâtiment"],
        "ar": ["شركة بناء", "مقاول", "construction"],
        "ja": ["建設会社", "工務店", "建築業者"],
        "es": ["empresa de construcción", "constructora", "contratista"],
        "de": ["Bauunternehmen", "Bauarbeiten", "Firmen"],
        "pt": ["empresa de construção", "construtora"],
        "it": ["azienda edile", "impresa di costruzioni"],
        "tr": ["inşaat şirketi", "müteahhit"],
        "ru": ["строительная компания", "подрядчик"],
        "zh": ["建筑公司", "施工公司"],
        "ko": ["건설 회사", "시공 회사"],
    },
    "pet_shop": {
        "osm_shop": "pet",
        "en": ["pet shop", "pet store", "pet supplies", "pet market"],
        "fr": ["animalerie", "magasin pour animaux"],
        "ar": ["محل حيوانات", "متجر حيوانات أليفة"],
        "ja": ["ペットショップ", "動物病院", "ペット用品店"],
        "es": ["tienda de mascotas", "pet shop"],
        "de": ["Tierhandlung", "Zoohandlung", "Tierversorgung"],
        "pt": ["pet shop", "loja de animais"],
        "it": ["negozio di animali", "pet shop"],
        "tr": ["pet shop", "hayvan dükkanı", "evcil hayvan mağazası"],
        "ru": ["зоомагазин", "магазин зоотоваров"],
        "zh": ["宠物店", "宠物用品店"],
        "ko": ["애완동물 가게", "펫숍"],
    },
    "cinema": {
        "osm_amenity": "cinema",
        "en": ["cinema", "movie theater", "film theater", "multiplex"],
        "fr": ["cinéma", "salle de cinéma"],
        "ar": ["سينما", "影院", "movie theater"],
        "ja": ["映画館", "シネマ", "映画劇場"],
        "es": ["cine", "sala de cine"],
        "de": ["Kino", "Filmtheater", "Kinotheater"],
        "pt": ["cinema", "cineteatro"],
        "it": ["cinema", "sala cinematografica"],
        "tr": ["sinema", "tiyatro"],
        "ru": ["кинотеатр", "кино"],
        "zh": ["电影院", "影院"],
        "ko": ["영화관", "시네마"],
    },
    "museum": {
        "osm_tourism": "museum",
        "en": ["museum", "art gallery", "exhibition"],
        "fr": ["musée", "galerie d'art"],
        "ar": ["متحف", "معرض فني"],
        "ja": ["博物館", "美術館", "ミュージアム"],
        "es": ["museo", "galería de arte"],
        "de": ["Museum", "Kunstgalerie"],
        "pt": ["museu", "galeria de arte"],
        "it": ["museo", "galleria d'arte"],
        "tr": ["müze", "sanat galerisi"],
        "ru": ["музей", "художественная галерея"],
        "zh": ["博物馆", "美术馆"],
        "ko": ["박물관", "미술관"],
    },
    "fast_food": {
        "osm_amenity": "fast_food",
        "en": ["fast food", "takeaway", "takeout", "quick service restaurant"],
        "fr": ["restauration rapide", "à emporter", "fast-food"],
        "ar": ["وجبات سريعة", "وجبات جاهزة"],
        "ja": ["ファストフード", "テイクアウト", "ファミレス"],
        "es": ["comida rápida", "para llevar"],
        "de": ["Schnellrestaurant", "Imbiss", "Fast Food"],
        "pt": ["fast food", "lanchonete", "comida rápida"],
        "it": ["fast food", "ristorazione rapida", "da asporto"],
        "tr": ["fast food", "hızlı yemek", "take away"],
        "ru": ["фастфуд", "быстрое питание"],
        "zh": ["快餐", "外卖"],
        "ko": ["패스트푸드", "패스트푸드점"],
    },
    "gas_station": {
        "osm_amenity": "fuel",
        "en": ["gas station", "petrol station", "fuel station", "service station"],
        "fr": ["station-service", "station essence"],
        "ar": ["محطة وقود", "محطة بنزين"],
        "ja": ["ガソリンスタンド", "給油所", "サービスステーション"],
        "es": ["gasolinera", "estación de servicio"],
        "de": ["Tankstelle", "Benzinstation"],
        "pt": ["posto de gasolina", "estação de combustível"],
        "it": ["benzinaio", "stazione di servizio"],
        "tr": ["benzin istasyonu", "akaryakıt istasyonu"],
        "ru": ["АЗС", "заправочная станция"],
        "zh": ["加油站"],
        "ko": ["주유소", "가스 스테이션"],
    },
    "laundry": {
        "osm_shop": "laundry",
        "en": ["laundry", "dry cleaner", "laundromat", "washing service"],
        "fr": ["laverie", "pressing", "nettoyage à sec"],
        "ar": ["مغسلة", "غسيل جاف"],
        "ja": ["洗濯屋", "クリーニング", "ランドリー"],
        "es": ["lavandería", "tintorería"],
        "de": ["Waschsalon", "Reinigung", "Wäscherei"],
        "pt": ["lavanderia", "lavanderia a seco"],
        "it": ["lavanderia", "lavaggio a secco"],
        "tr": ["çamaşırhane", "kuru temizleme"],
        "ru": ["прачечная", "химчистка"],
        "zh": ["洗衣店", "干洗店"],
        "ko": ["세탁소", "드라이클리닝"],
    },
    "locksmith": {
        "osm_craft": "locksmith",
        "en": ["locksmith", "lock and key", "key maker"],
        "fr": ["serrurier", "fabricant de clés"],
        "ar": ["قفل", "صانع مفاتيح"],
        "ja": ["鍵屋", "解錬屋", "南京錠"],
        "es": ["cerrajero", "llavero"],
        "de": ["Schlosser", "Schlüsseldienst"],
        "pt": ["chaveiro", "serviço de chaveiro"],
        "it": ["fabbro", "servizio di serratura"],
        "tr": ["çilingir", "anahtarcı"],
        "ru": ["слесарь", "замочник"],
        "zh": ["锁匠", "开锁服务"],
        "ko": ["자물쇠 공", "열쇠공"],
    },
    "carpenter": {
        "osm_craft": "carpenter",
        "en": ["carpenter", "woodworker", "cabinet maker"],
        "fr": ["charpentier", "menuisier", "ébéniste"],
        "ar": ["نجار", "خشب"],
        "ja": ["大工", "木工", "家具職人"],
        "es": ["carpintero", "ebanista"],
        "de": ["Tischler", "Zimmermann", "Schreiner"],
        "pt": ["carpinteiro", "marceneiro"],
        "it": ["falegname", "ebanista"],
        "tr": ["marangoz", "ahşap ustası"],
        "ru": ["плотник", "столяр"],
        "zh": ["木匠", "家具工匠"],
        "ko": ["목수", "가구공예사"],
    },
    "insurance": {
        "osm_office": "insurance",
        "en": ["insurance", "insurance agency", "insurance company"],
        "fr": ["assurance", "agence d'assurance"],
        "ar": ["تأمين", "وكالة تأمين"],
        "ja": ["保険", "保険会社", "保険代理店"],
        "es": ["seguros", "agencia de seguros"],
        "de": ["Versicherung", "Versicherungsagentur"],
        "pt": ["seguros", "agência de seguros"],
        "it": ["assicurazione", "agenzia assicurativa"],
        "tr": ["sigorta", "sigorta acentesi"],
        "ru": ["страхование", "страховое агентство"],
        "zh": ["保险", "保险公司", "保险代理"],
        "ko": ["보험", "보험사", "보험 대리점"],
    },
    "art_gallery": {
        "osm_shop": "art",
        "en": ["art gallery", "gallery", "art studio"],
        "fr": ["galerie d'art", "atelier d'art"],
        "ar": ["معرض فني", "استوديو فني"],
        "ja": ["ギャラリー", "アートギャラリー", "美術画廊"],
        "es": ["galería de arte", "estudio de arte"],
        "de": ["Kunstgalerie", "Galerie"],
        "pt": ["galeria de arte", "estúdio de arte"],
        "it": ["galleria d'arte", "studio d'arte"],
        "tr": ["sanat galerisi", "galeri"],
        "ru": ["художественная галерея", "галерея"],
        "zh": ["画廊", "艺术画廊"],
        "ko": ["갤러리", "미술관"],
    },
    "toy_store": {
        "osm_shop": "toys",
        "en": ["toy store", "toy shop", "toy market"],
        "fr": ["magasin de jouets", "jouets"],
        "ar": ["محل ألعاب", "متجر ألعاب"],
        "ja": ["おもちゃ屋", "トイショップ"],
        "es": ["tienda de juguetes", "juguetería"],
        "de": ["Spielwarenladen", "Spielzeuggeschäft"],
        "pt": ["loja de brinquedos", "brinquedos"],
        "it": ["negozio di giocattoli", "giocattoli"],
        "tr": ["oyuncakçı", "oyuncak mağazası"],
        "ru": ["магазин игрушек", "игрушки"],
        "zh": ["玩具店", "玩具商店"],
        "ko": ["장난감 가게", "토이숍"],
    },
    "music_store": {
        "osm_shop": "music",
        "en": ["music store", "instrument shop", "musical instruments"],
        "fr": ["magasin de musique", "instruments de musique"],
        "ar": ["محل موسيقى", "آلات موسيقية"],
        "ja": ["楽器店", "音楽店", "インストゥルメントショップ"],
        "es": ["tienda de música", "instrumentos musicales"],
        "de": ["Musikgeschäft", "Instrumentenhandlung"],
        "pt": ["loja de música", "instrumentos musicais"],
        "it": ["negozio di musica", "strumenti musicali"],
        "tr": ["müzik dükkanı", "enstrüman mağazası"],
        "ru": ["музыкальный магазин", "музыкальные инструменты"],
        "zh": ["乐器店", "音乐商店"],
        "ko": ["악기점", "음악 매장"],
    },
    "bike_shop": {
        "osm_shop": "bicycle",
        "en": ["bike shop", "bicycle store", "cycle shop"],
        "fr": ["magasin de vélos", "cycles"],
        "ar": ["محل دراجات", "متجر دراجات"],
        "ja": ["自転車屋", "バイクショップ"],
        "es": ["tienda de bicicletas", "ciclo"],
        "de": ["Fahrradgeschäft", "Fahrradladen"],
        "pt": ["loja de bicicletas", "bicicletas"],
        "it": ["negozio di biciclette", "cicli"],
        "tr": ["bisikletçi", "bisiklet mağazası"],
        "ru": ["веломагазин", "велосипеды"],
        "zh": ["自行车店", "单车店"],
        "ko": ["자전거 가게", "바이크숍"],
    },
    "car_dealer": {
        "osm_shop": "car",
        "en": ["car dealer", "car showroom", "automobile dealer"],
        "fr": ["concessionnaire automobile", "garage"],
        "ar": ["وكيل سيارات", "معرض سيارات"],
        "ja": ["自動車販売", "カーディーラー", "自動車ショップ"],
        "es": ["concesionario de coches", "automovil"],
        "de": ["Autohaus", "Autohändler"],
        "pt": ["concessionária de carros", "dealer de veículos"],
        "it": ["concessionario auto", "automobile"],
        "tr": ["araba bayisi", "otomobil galerisi"],
        "ru": ["автосалон", "дилерский центр"],
        "zh": ["汽车经销商", "汽车4S店"],
        "ko": ["자동차 대리점", "카 딜러"],
    },
    "dry_cleaner": {
        "osm_shop": "dry_cleaning",
        "en": ["dry cleaner", "dry cleaning", "cleaning service"],
        "fr": ["pressing", "nettoyage à sec"],
        "ar": ["غسيل جاف", "مغسلة"],
        "ja": ["クリーニング", "ドライクリーニング"],
        "es": ["tintorería", "limpieza en seco"],
        "de": ["Reinigung", "Wäscherei"],
        "pt": ["lavanderia a seco", "limpeza seca"],
        "it": ["lavaggio a secco", "lavanderia"],
        "tr": ["kuru temizleme"],
        "ru": ["химчистка", "чистка"],
        "zh": ["干洗店", "干洗服务"],
        "ko": ["드라이클리닝", "세탁소"],
    },
    "shoe_store": {
        "osm_shop": "shoes",
        "en": ["shoe store", "shoe shop", "footwear"],
        "fr": ["magasin de chaussures", "chaussures"],
        "ar": ["محل أحذية", "متجر أحذية"],
        "ja": ["靴屋", "シューズショップ"],
        "es": ["zapatería", "tienda de zapatos"],
        "de": ["Schuhgeschäft", "Schuhladen"],
        "pt": ["loja de sapatos", "sapataria"],
        "it": ["negozio di scarpe", "calzature"],
        "tr": ["ayakkabı mağazası", "ayakkabıcı"],
        "ru": ["обувной магазин", "обувь"],
        "zh": ["鞋店", "鞋类商店"],
        "ko": ["신발 가게", "슈즈숍"],
    },
    "sports_store": {
        "osm_shop": "sports",
        "en": ["sports store", "sporting goods", "sports shop"],
        "fr": ["magasin de sport", "articles de sport"],
        "ar": ["محل رياضة", "متجر رياضي"],
        "ja": ["スポーツ用品店", "スポーツショップ"],
        "es": ["tienda de deportes", "artículos deportivos"],
        "de": ["Sportgeschäft", "Sportartikel"],
        "pt": ["loja de esportes", "artigos esportivos"],
        "it": ["negozio di articoli sportivi", "sport"],
        "tr": ["spor mağazası", "spor malzemeleri"],
        "ru": ["спортивный магазин", "спортивные товары"],
        "zh": ["体育用品店", "运动商店"],
        "ko": ["스포츠 용품점", "스포츠숍"],
    },
    "gift_shop": {
        "osm_shop": "gift",
        "en": ["gift shop", "souvenir shop", "souvenirs"],
        "fr": ["boutique de cadeaux", "souvenirs"],
        "ar": ["محل هدايا", "متجر هدايا"],
        "ja": ["ギフトショップ", "お土産屋", "サウベニール"],
        "es": ["tienda de regalos", "tienda de recuerdos"],
        "de": ["Geschenkeladen", "Souvenirgeschäft"],
        "pt": ["loja de presentes", "loja de lembranças"],
        "it": ["negozio di regali", "souvenir"],
        "tr": ["hediyelik eşya", "souvenir dükkanı"],
        "ru": ["магазин подарков", "сувенирный магазин"],
        "zh": ["礼品店", "纪念品店"],
        "ko": ["선물 가게", "기념품점"],
    },
    "stationery": {
        "osm_shop": "stationery",
        "en": ["stationery", "office supplies", "paper goods"],
        "fr": ["papeterie", "fournitures de bureau"],
        "ar": ["قرطاسية", "مستلزمات مكتبية"],
        "ja": ["文具店", "文房具店", "オフィスサプライ"],
        "es": ["papelería", "artículos de oficina"],
        "de": ["Bürobedarf", "Schreibwaren"],
        "pt": ["papelaria", "material de escritório"],
        "it": ["cartoleria", "forniture per ufficio"],
        "tr": [" kırtasiye", "ofis malzemeleri"],
        "ru": ["канцтовары", "офисные принадлежности"],
        "zh": ["文具店", "办公用品"],
        "ko": ["문구점", "오피스 용품"],
    },
}


# =============================================================================
# REVERSE MAP: Any language input → English business type
# =============================================================================
REVERSE_MAP = {
}


for eng_name, translations in BUSINESS_TYPES.items():
    REVERSE_MAP[eng_name] = eng_name
    for lang_words in translations.values():
        if isinstance(lang_words, list):
            for word in lang_words:
                REVERSE_MAP[word.lower().strip()] = eng_name
        elif isinstance(lang_words, str):
            REVERSE_MAP[lang_words.lower().strip()] = eng_name


# =============================================================================
# COUNTRY → LANGUAGE PRIORITY (for Accept-Language header)
# =============================================================================
COUNTRY_LANGUAGES = {
    "aarhus": ["da", "en"],
    "abidjan": ["fr", "en"],
    "abu dhabi": ["ar", "en"],
    "abuja": ["en"],
    "accra": ["en"],
    "addis ababa": ["am", "en"],
    "adelaide": ["en"],
    "afghanistan": ["ps", "fa", "en"],
    "agadir": ["ar", "fr", "en"],
    "ahmedabad": ["en"],
    "albania": ["sq", "en"],
    "albuquerque": ["en", "es"],
    "alexandria": ["ar", "en"],
    "algeria": ["ar", "fr", "en"],
    "algiers": ["ar", "fr", "en"],
    "almaty": ["kk", "ru"],
    "amman": ["ar", "en"],
    "amsterdam": ["nl", "en"],
    "andorra": ["ca", "en"],
    "angola": ["pt", "en"],
    "ankara": ["tr", "en"],
    "antananarivo": ["fr", "en"],
    "antigua and barbuda": ["en"],
    "antwerp": ["nl", "en"],
    "apia": ["sm", "en"],
    "arequipa": ["es", "en"],
    "argentina": ["es", "en"],
    "arlington": ["en"],
    "armenia": ["hy", "en"],
    "aruba": ["nl", "en"],
    "ashgabat": ["tk", "en"],
    "asmara": ["ti", "ar"],
    "asuncion": ["es", "en"],
    "athens": ["el", "en"],
    "atlanta": ["en"],
    "auckland": ["en"],
    "austin": ["en"],
    "australia": ["en"],
    "austria": ["de", "en"],
    "azerbaijan": ["az", "en"],
    "baghdad": ["ar", "en"],
    "bahamas": ["en"],
    "bahrain": ["ar", "en"],
    "baku": ["az", "en"],
    "bali": ["id", "en"],
    "baltimore": ["en"],
    "bamako": ["fr", "en"],
    "bandar seri begawan": ["ms", "en"],
    "bandung": ["id", "en"],
    "bangalore": ["en"],
    "bangkok": ["th", "en"],
    "bangladesh": ["bn", "en"],
    "bangui": ["fr", "en"],
    "banjul": ["en"],
    "barbados": ["en"],
    "barcelona": ["es", "ca", "en"],
    "basel": ["de", "en"],
    "basra": ["ar", "en"],
    "beijing": ["zh", "en"],
    "beirut": ["ar", "en"],
    "belarus": ["be", "ru", "en"],
    "belgium": ["fr", "nl", "de", "en"],
    "belgrade": ["sr", "en"],
    "belize": ["en", "es"],
    "belmopan": ["en"],
    "belo horizonte": ["pt", "en"],
    "benin": ["fr", "en"],
    "bergen": ["no", "en"],
    "berlin": ["de", "en"],
    "bern": ["de", "fr", "en"],
    "bhutan": ["dz", "en"],
    "bilbao": ["es", "en"],
    "birmingham": ["en"],
    "bishkek": ["ky", "ru"],
    "bissau": ["pt"],
    "bogota": ["es", "en"],
    "bolivia": ["es", "en"],
    "bonaire": ["nl", "en"],
    "bordeaux": ["fr", "en"],
    "bosnia and herzegovina": ["bs", "hr", "en"],
    "boston": ["en"],
    "botswana": ["en", "tn"],
    "brasilia": ["pt", "en"],
    "bratislava": ["sk", "en"],
    "brazil": ["pt", "en"],
    "brazzaville": ["fr", "en"],
    "bridgetown": ["en"],
    "brisbane": ["en"],
    "bristol": ["en"],
    "brno": ["cs", "en"],
    "brunei": ["ms", "en"],
    "brussels": ["fr", "nl", "en"],
    "bucharest": ["ro", "en"],
    "budapest": ["hu", "en"],
    "buenos aires": ["es", "en"],
    "bujumbura": ["fr", "en"],
    "bulgaria": ["bg", "en"],
    "burkina faso": ["fr", "en"],
    "burundi": ["fr", "en"],
    "busan": ["ko", "en"],
    "cabo verde": ["pt", "en"],
    "cairo": ["ar", "en"],
    "calgary": ["en"],
    "cali": ["es", "en"],
    "cambodia": ["km", "en"],
    "cameroon": ["fr", "en"],
    "canada": ["en", "fr"],
    "cape town": ["en"],
    "caracas": ["es", "en"],
    "cardiff": ["en"],
    "casablanca": ["ar", "fr", "en"],
    "cebu": ["en", "tl"],
    "central african republic": ["fr", "en"],
    "chad": ["fr", "ar", "en"],
    "chengdu": ["zh", "en"],
    "chennai": ["en"],
    "chiang mai": ["th", "en"],
    "chicago": ["en"],
    "chile": ["es", "en"],
    "china": ["zh", "en"],
    "chisinau": ["ro", "en"],
    "chittagong": ["bn", "en"],
    "christchurch": ["en"],
    "cluj-napoca": ["ro", "en"],
    "cologne": ["de", "en"],
    "colombia": ["es", "en"],
    "colombo": ["si", "en"],
    "colorado springs": ["en"],
    "comoros": ["ar", "fr"],
    "conakry": ["fr", "en"],
    "congo": ["fr", "en"],
    "copenhagen": ["da", "en"],
    "cordoba": ["es", "en"],
    "cork": ["en"],
    "costa rica": ["es", "en"],
    "croatia": ["hr", "en"],
    "cuba": ["es", "en"],
    "curacao": ["nl", "en"],
    "cyprus": ["el", "tr", "en"],
    "czech republic": ["cs", "en"],
    "czechia": ["cs", "en"],
    "da nang": ["vi", "en"],
    "dakar": ["fr", "en"],
    "dallas": ["en"],
    "damascus": ["ar", "en"],
    "dar es salaam": ["sw", "en"],
    "delhi": ["hi", "en"],
    "democratic republic of the congo": ["fr", "en"],
    "denmark": ["da", "en"],
    "denver": ["en"],
    "detroit": ["en"],
    "dhaka": ["bn", "en"],
    "dili": ["pt", "en"],
    "djibouti": ["ar", "fr"],
    "djibouti city": ["ar", "fr"],
    "dodoma": ["sw", "en"],
    "doha": ["ar", "en"],
    "dominica": ["en"],
    "dominican republic": ["es", "en"],
    "dortmund": ["de", "en"],
    "douala": ["fr", "en"],
    "dubai": ["ar", "en"],
    "dublin": ["en"],
    "durban": ["en"],
    "dushanbe": ["tg", "ru"],
    "dusseldorf": ["de", "en"],
    "east timor": ["pt", "en"],
    "ecuador": ["es", "en"],
    "edinburgh": ["en"],
    "egypt": ["ar", "en"],
    "el salvador": ["es", "en"],
    "equatorial guinea": ["es", "fr"],
    "eritrea": ["ti", "ar", "en"],
    "estonia": ["et", "en"],
    "eswatini": ["en", "ss"],
    "ethiopia": ["am", "en"],
    "fes": ["ar", "fr", "en"],
    "fiji": ["en", "fj"],
    "finland": ["fi", "sv", "en"],
    "florence": ["it", "en"],
    "fortaleza": ["pt", "en"],
    "france": ["fr", "en"],
    "frankfurt": ["de", "en"],
    "freetown": ["en"],
    "fresno": ["en", "es"],
    "fukuoka": ["ja", "en"],
    "funafuti": ["en"],
    "gabon": ["fr", "en"],
    "gaborone": ["en"],
    "gambia": ["en"],
    "geneva": ["fr", "en"],
    "georgia": ["ka", "en"],
    "germany": ["de", "en"],
    "ghana": ["en"],
    "ghent": ["nl", "en"],
    "glasgow": ["en"],
    "gold coast": ["en"],
    "gothenburg": ["sv", "en"],
    "graz": ["de", "en"],
    "greece": ["el", "en"],
    "grenada": ["en"],
    "guadalajara": ["es", "en"],
    "guadeloupe": ["fr", "en"],
    "guangzhou": ["zh", "en"],
    "guatemala": ["es", "en"],
    "guatemala city": ["es", "en"],
    "guayaquil": ["es", "en"],
    "guinea": ["fr", "en"],
    "guinea-bissau": ["pt", "fr"],
    "haifa": ["he", "en"],
    "haiti": ["fr", "ht"],
    "hamburg": ["de", "en"],
    "hangzhou": ["zh", "en"],
    "hanoi": ["vi", "en"],
    "harare": ["en"],
    "havana": ["es", "en"],
    "helsinki": ["fi", "sv", "en"],
    "hiroshima": ["ja", "en"],
    "ho chi minh": ["vi", "en"],
    "honduras": ["es", "en"],
    "hong kong": ["zh", "en"],
    "honiara": ["en"],
    "houston": ["en"],
    "hungary": ["hu", "en"],
    "hyderabad": ["en"],
    "iceland": ["is", "en"],
    "incheon": ["ko", "en"],
    "india": ["hi", "en"],
    "indonesia": ["id", "en"],
    "iran": ["fa", "en"],
    "iraq": ["ar", "en"],
    "ireland": ["en"],
    "isfahan": ["fa", "en"],
    "islamabad": ["ur", "en"],
    "israel": ["he", "en"],
    "istanbul": ["tr", "en"],
    "italy": ["it", "en"],
    "ivory coast": ["fr", "en"],
    "jacksonville": ["en"],
    "jaipur": ["en"],
    "jakarta": ["id", "en"],
    "jamaica": ["en"],
    "japan": ["ja", "en"],
    "jeddah": ["ar", "en"],
    "jerusalem": ["he", "ar", "en"],
    "johannesburg": ["en"],
    "jordan": ["ar", "en"],
    "juba": ["en"],
    "kabul": ["ps", "fa"],
    "kampala": ["en", "sw"],
    "kano": ["en"],
    "kansas city": ["en"],
    "karachi": ["ur", "en"],
    "kathmandu": ["ne", "en"],
    "kawasaki": ["ja", "en"],
    "kazakhstan": ["kk", "ru", "en"],
    "kenya": ["en", "sw"],
    "kharkiv": ["uk", "ru"],
    "khartoum": ["ar", "en"],
    "kigali": ["rw", "en", "fr"],
    "kingston": ["en"],
    "kinshasa": ["fr", "en"],
    "kiribati": ["en"],
    "kolkata": ["en"],
    "krakow": ["pl", "en"],
    "kuala lumpur": ["ms", "en"],
    "kumasi": ["en"],
    "kuwait": ["ar", "en"],
    "kuwait city": ["ar", "en"],
    "kyiv": ["uk", "ru"],
    "kyoto": ["ja", "en"],
    "kyrgyzstan": ["ky", "ru", "en"],
    "la paz": ["es", "en"],
    "lagos": ["en"],
    "lahore": ["ur", "en"],
    "laos": ["lo", "en"],
    "las vegas": ["en"],
    "latvia": ["lv", "en"],
    "lebanon": ["ar", "en"],
    "leeds": ["en"],
    "leipzig": ["de", "en"],
    "lesotho": ["en"],
    "liberia": ["en"],
    "libreville": ["fr", "en"],
    "libya": ["ar", "en"],
    "liechtenstein": ["de", "en"],
    "liege": ["fr", "en"],
    "lille": ["fr", "en"],
    "lilongwe": ["en"],
    "lima": ["es", "en"],
    "lisbon": ["pt", "en"],
    "lithuania": ["lt", "en"],
    "liverpool": ["en"],
    "ljubljana": ["sl", "en"],
    "lodz": ["pl", "en"],
    "lome": ["fr", "en"],
    "london": ["en"],
    "long beach": ["en"],
    "los angeles": ["en", "es"],
    "luanda": ["pt", "en"],
    "lucknow": ["en"],
    "lusaka": ["en"],
    "luxembourg": ["fr", "de", "en"],
    "luxembourg city": ["fr", "de"],
    "lyon": ["fr", "en"],
    "macau": ["zh", "pt", "en"],
    "madagascar": ["fr", "en"],
    "madrid": ["es", "en"],
    "majuro": ["en"],
    "makassar": ["id", "en"],
    "malabo": ["es", "fr"],
    "malaga": ["es", "en"],
    "malawi": ["en"],
    "malaysia": ["ms", "en"],
    "maldives": ["dv", "en"],
    "male": ["dv", "en"],
    "mali": ["fr", "en"],
    "malta": ["mt", "en"],
    "managua": ["es", "en"],
    "manama": ["ar", "en"],
    "manchester": ["en"],
    "manila": ["en", "tl"],
    "maputo": ["pt", "en"],
    "marrakech": ["ar", "fr", "en"],
    "marseille": ["fr", "en"],
    "marshall islands": ["en"],
    "martinique": ["fr", "en"],
    "maseru": ["en"],
    "mauritania": ["ar", "en"],
    "mauritius": ["en", "fr"],
    "mbabane": ["en"],
    "medan": ["id", "en"],
    "medellin": ["es", "en"],
    "melbourne": ["en"],
    "mesa": ["en"],
    "mexico": ["es", "en"],
    "mexico city": ["es", "en"],
    "miami": ["en", "es"],
    "micronesia": ["en"],
    "milan": ["it", "en"],
    "milwaukee": ["en"],
    "minneapolis": ["en"],
    "minsk": ["be", "ru"],
    "mogadishu": ["so", "ar"],
    "moldova": ["ro", "en"],
    "mombasa": ["en", "sw"],
    "monaco": ["fr", "en"],
    "mongolia": ["mn", "en"],
    "monrovia": ["en"],
    "montenegro": ["sr", "en"],
    "monterrey": ["es", "en"],
    "montevideo": ["es", "en"],
    "montpellier": ["fr", "en"],
    "montreal": ["fr", "en"],
    "morocco": ["ar", "fr", "en"],
    "moroni": ["ar", "fr"],
    "moscow": ["ru", "en"],
    "mozambique": ["pt", "en"],
    "mumbai": ["hi", "en"],
    "munich": ["de", "en"],
    "muscat": ["ar", "en"],
    "myanmar": ["my", "en"],
    "nagoya": ["ja", "en"],
    "nairobi": ["en", "sw"],
    "namibia": ["en"],
    "nanjing": ["zh", "en"],
    "nantes": ["fr", "en"],
    "naples": ["it", "en"],
    "nashville": ["en"],
    "nassau": ["en"],
    "nauru": ["en"],
    "ndjamena": ["fr", "ar"],
    "nepal": ["ne", "en"],
    "netherlands": ["nl", "en"],
    "new york": ["en", "es"],
    "new zealand": ["en"],
    "niamey": ["fr", "en"],
    "nicaragua": ["es", "en"],
    "nice": ["fr", "en"],
    "nicosia": ["el", "tr"],
    "niger": ["fr", "en"],
    "nigeria": ["en"],
    "north korea": ["ko"],
    "north macedonia": ["mk", "en"],
    "norway": ["no", "en"],
    "nouakchott": ["ar", "en"],
    "novosibirsk": ["ru", "en"],
    "nuku'alofa": ["to", "en"],
    "nur-sultan": ["kk", "ru"],
    "oakland": ["en"],
    "odessa": ["uk", "ru"],
    "omaha": ["en"],
    "oman": ["ar", "en"],
    "osaka": ["ja", "en"],
    "oslo": ["no", "en"],
    "ottawa": ["en", "fr"],
    "ouagadougou": ["fr", "en"],
    "pakistan": ["ur", "en"],
    "palestine": ["ar", "en"],
    "palikir": ["en"],
    "panama": ["es", "en"],
    "panama city": ["es", "en"],
    "papua new guinea": ["en", "tpi"],
    "paraguay": ["es", "en"],
    "paramaribo": ["nl", "en"],
    "paris": ["fr", "en"],
    "pattaya": ["th", "en"],
    "penang": ["ms", "en"],
    "perth": ["en"],
    "peru": ["es", "en"],
    "philadelphia": ["en"],
    "philippines": ["en", "tl"],
    "phnom penh": ["km", "en"],
    "phoenix": ["en"],
    "phuket": ["th", "en"],
    "plovdiv": ["bg", "en"],
    "podgorica": ["sr", "en"],
    "poland": ["pl", "en"],
    "port louis": ["en", "fr"],
    "port moresby": ["en"],
    "port of spain": ["en"],
    "port vila": ["bi", "en", "fr"],
    "portland": ["en"],
    "porto": ["pt", "en"],
    "porto-novo": ["fr", "en"],
    "portugal": ["pt", "en"],
    "poznan": ["pl", "en"],
    "prague": ["cs", "en"],
    "praia": ["pt", "en"],
    "pretoria": ["en"],
    "puerto rico": ["es", "en"],
    "pune": ["en"],
    "pyongyang": ["ko"],
    "qatar": ["ar", "en"],
    "quito": ["es", "en"],
    "rabat": ["ar", "fr", "en"],
    "raleigh": ["en"],
    "ramallah": ["ar", "en"],
    "reykjavik": ["is", "en"],
    "riga": ["lv", "en"],
    "rio de janeiro": ["pt", "en"],
    "riyadh": ["ar", "en"],
    "romania": ["ro", "en"],
    "rome": ["it", "en"],
    "rosario": ["es", "en"],
    "rotterdam": ["nl", "en"],
    "russia": ["ru", "en"],
    "rwanda": ["rw", "en", "fr"],
    "sacramento": ["en"],
    "saint barthelemy": ["fr", "en"],
    "saint kitts and nevis": ["en"],
    "saint lucia": ["en"],
    "saint martin": ["fr", "en"],
    "saint petersburg": ["ru", "en"],
    "saint vincent and the grenadines": ["en"],
    "salvador": ["pt", "en"],
    "samoa": ["sm", "en"],
    "san antonio": ["en", "es"],
    "san diego": ["en", "es"],
    "san francisco": ["en"],
    "san jose": ["es", "en"],
    "san juan": ["es", "en"],
    "san marino": ["it", "en"],
    "san salvador": ["es", "en"],
    "sana'a": ["ar", "en"],
    "santa cruz": ["es", "en"],
    "santiago": ["es", "en"],
    "santo domingo": ["es", "en"],
    "sao paulo": ["pt", "en"],
    "sao tome": ["pt"],
    "sao tome and principe": ["pt"],
    "sapporo": ["ja", "en"],
    "sarajevo": ["bs", "hr", "en"],
    "saudi arabia": ["ar", "en"],
    "seattle": ["en"],
    "semarang": ["id", "en"],
    "senegal": ["fr", "en"],
    "seoul": ["ko", "en"],
    "serbia": ["sr", "en"],
    "seville": ["es", "en"],
    "seychelles": ["en", "fr"],
    "shanghai": ["zh", "en"],
    "sharjah": ["ar", "en"],
    "shenzhen": ["zh", "en"],
    "siem reap": ["km", "en"],
    "sierra leone": ["en"],
    "singapore": ["en", "zh", "ms", "ta"],
    "sint maarten": ["nl", "en"],
    "skopje": ["mk", "en"],
    "slovakia": ["sk", "en"],
    "slovenia": ["sl", "en"],
    "sofia": ["bg", "en"],
    "solomon islands": ["en"],
    "somalia": ["so", "ar", "en"],
    "south africa": ["en", "zu", "af"],
    "south korea": ["ko", "en"],
    "south sudan": ["en"],
    "spain": ["es", "en"],
    "split": ["hr", "en"],
    "sri lanka": ["si", "en"],
    "stockholm": ["sv", "en"],
    "strasbourg": ["fr", "en"],
    "stuttgart": ["de", "en"],
    "sudan": ["ar", "en"],
    "surabaya": ["id", "en"],
    "suriname": ["nl", "en"],
    "suva": ["en"],
    "sweden": ["sv", "en"],
    "switzerland": ["de", "fr", "it", "en"],
    "sydney": ["en"],
    "syria": ["ar", "en"],
    "taipei": ["zh", "en"],
    "taiwan": ["zh", "en"],
    "tajikistan": ["tg", "ru", "en"],
    "tallinn": ["et", "en"],
    "tampa": ["en"],
    "tampere": ["fi", "en"],
    "tangier": ["ar", "fr", "en"],
    "tanzania": ["sw", "en"],
    "tarawa": ["en"],
    "tashkent": ["uz", "ru"],
    "tbilisi": ["ka", "en"],
    "tegucigalpa": ["es", "en"],
    "tehran": ["fa", "en"],
    "tel aviv": ["he", "en"],
    "thailand": ["th", "en"],
    "the hague": ["nl", "en"],
    "thessaloniki": ["el", "en"],
    "thimphu": ["dz", "en"],
    "tianjin": ["zh", "en"],
    "tirana": ["sq", "en"],
    "togo": ["fr", "en"],
    "tokyo": ["ja", "en"],
    "tonga": ["to", "en"],
    "toronto": ["en"],
    "toulouse": ["fr", "en"],
    "trinidad and tobago": ["en"],
    "tripoli": ["ar", "en"],
    "tucson": ["en", "es"],
    "tulsa": ["en"],
    "tunis": ["ar", "fr", "en"],
    "tunisia": ["ar", "fr", "en"],
    "turin": ["it", "en"],
    "turkey": ["tr", "en"],
    "turkmenistan": ["tk", "en"],
    "turku": ["fi", "sv", "en"],
    "tuvalu": ["en"],
    "uae": ["ar", "en"],
    "uganda": ["en", "sw"],
    "uk": ["en"],
    "ukraine": ["uk", "ru", "en"],
    "ulan bator": ["mn", "en"],
    "united arab emirates": ["ar", "en"],
    "united kingdom": ["en"],
    "united states": ["en", "es"],
    "us virgin islands": ["en"],
    "usa": ["en", "es"],
    "utrecht": ["nl", "en"],
    "uzbekistan": ["uz", "ru", "en"],
    "vaduz": ["de", "en"],
    "valencia": ["es", "en"],
    "valletta": ["mt", "en"],
    "valparaiso": ["es", "en"],
    "vancouver": ["en"],
    "vanuatu": ["bi", "en", "fr"],
    "vatican city": ["it", "la"],
    "venice": ["it", "en"],
    "victoria": ["en", "fr"],
    "vienna": ["de", "en"],
    "vientiane": ["lo", "en"],
    "vietnam": ["vi", "en"],
    "vilnius": ["lt", "en"],
    "virginia beach": ["en"],
    "warsaw": ["pl", "en"],
    "washington": ["en"],
    "wellington": ["en"],
    "windhoek": ["en"],
    "wroclaw": ["pl", "en"],
    "wuhan": ["zh", "en"],
    "xian": ["zh", "en"],
    "yangon": ["my", "en"],
    "yaounde": ["fr", "en"],
    "yaren": ["en"],
    "yemen": ["ar", "en"],
    "yerevan": ["hy", "en"],
    "yokohama": ["ja", "en"],
    "zagreb": ["hr", "en"],
    "zambia": ["en"],
    "zimbabwe": ["en"],
    "zurich": ["de", "en"],
}

# =============================================================================
# LANGUAGE CODE → ACCEPT-LANGUAGE HEADER
# =============================================================================
ACCEPT_LANGUAGE_HEADERS = {
    "ar": "ar,en;q=0.9,fr;q=0.8",
    "ja": "ja,en;q=0.9",
    "fr": "fr,en;q=0.9",
    "en": "en-US,en;q=0.9",
    "es": "es,en;q=0.9",
    "de": "de,en;q=0.9",
    "pt": "pt-BR,pt;q=0.9,en;q=0.8",
    "it": "it,en;q=0.9",
    "tr": "tr,en;q=0.9",
    "ru": "ru,en;q=0.9",
    "zh": "zh-CN,zh;q=0.9,en;q=0.8",
    "ko": "ko,en;q=0.9",
    "hi": "hi,en;q=0.9",
    "th": "th,en;q=0.9",
    "vi": "vi,en;q=0.9",
    "id": "id,en;q=0.9",
    "ms": "ms,en;q=0.9",
    "nl": "nl,en;q=0.9",
    "pl": "pl,en;q=0.9",
    "sv": "sv,en;q=0.9",
    "no": "no,en;q=0.9",
    "da": "da,en;q=0.9",
    "fi": "fi,en;q=0.9",
    "el": "el,en;q=0.9",
    "cs": "cs,en;q=0.9",
    "tl": "tl,en;q=0.9",
    "zu": "zu,en;q=0.9",
    "af": "af,en;q=0.9",
    "ca": "ca,en;q=0.9",
    "hy": "hy,en;q=0.9",
    "az": "az,en;q=0.9",
    "ka": "ka,en;q=0.9",
    "si": "si,en;q=0.9",
    "am": "am,en;q=0.9",
    "rw": "rw,en;q=0.9",
    "my": "my,en;q=0.9",
    "ne": "ne,en;q=0.9",
    "bn": "bn,en;q=0.9",
    "ur": "ur,en;q=0.9",
    "fa": "fa,en;q=0.9",
    "ps": "ps,en;q=0.9",
    "tg": "tg,en;q=0.9",
    "tk": "tk,en;q=0.9",
    "uz": "uz,en;q=0.9",
    "kk": "kk,en;q=0.9",
    "ky": "ky,en;q=0.9",
    "mt": "mt,en;q=0.9",
    "sq": "sq,en;q=0.9",
    "bs": "bs,en;q=0.9",
    "hr": "hr,en;q=0.9",
    "sk": "sk,en;q=0.9",
    "sl": "sl,en;q=0.9",
    "sr": "sr,en;q=0.9",
    "mk": "mk,en;q=0.9",
    "bg": "bg,en;q=0.9",
    "ro": "ro,en;q=0.9",
    "hu": "hu,en;q=0.9",
    "is": "is,en;q=0.9",
    "et": "et,en;q=0.9",
    "lv": "lv,en;q=0.9",
    "lt": "lt,en;q=0.9",
    "sw": "sw,en;q=0.9",
    "to": "to,en;q=0.9",
    "sm": "sm,en;q=0.9",
    "bi": "bi,en;q=0.9",
    "tpi": "tpi,en;q=0.9",
    "ht": "ht,en;q=0.9",
    "be": "be,en;q=0.9",
    "uk": "uk,en;q=0.9",
    "km": "km,en;q=0.9",
    "lo": "lo,en;q=0.9",
    "dz": "dz,en;q=0.9",
    "mn": "mn,en;q=0.9",
    "dv": "dv,en;q=0.9",
    "tn": "tn,en;q=0.9",
    "ss": "ss,en;q=0.9",
    "rw": "rw,en;q=0.9",
    "ny": "ny,en;q=0.9",
    "sn": "sn,en;q=0.9",
    "yo": "yo,en;q=0.9",
    "ig": "ig,en;q=0.9",
    "ha": "ha,en;q=0.9",
    "so": "so,en;q=0.9",
    "mg": "mg,en;q=0.9",
    "sg": "sg,en;q=0.9",
    "rn": "rn,en;q=0.9",
    "lg": "lg,en;q=0.9",
    "ak": "ak,en;q=0.9",
    "tw": "tw,en;q=0.9",
    "ff": "ff,en;q=0.9",
    "wo": "wo,en;q=0.9",
    "bm": "bm,en;q=0.9",
    "dyu": "dyu,en;q=0.9",
    "mos": "mos,en;q=0.9",
    "ha": "ha,en;q=0.9",
    "yo": "yo,en;q=0.9",
    "ig": "ig,en;q=0.9",
    "pcm": "pcm,en;q=0.9",
    "zu": "zu,en;q=0.9",
    "xh": "xh,en;q=0.9",
    "st": "st,en;q=0.9",
    "ts": "ts,en;q=0.9",
    "ve": "ve,en;q=0.9",
    "nr": "nr,en;q=0.9",
}


# =============================================================================
# CONTACT PATHS BY LANGUAGE
# =============================================================================
CONTACT_PATHS_BY_LANG = {
    "en": [
        "/contact", "/contact-us", "/contact.html", "/contact.php",
        "/about", "/about-us", "/about.html",
        "/team", "/our-team", "/staff",
        "/support", "/help",
    ],
    "fr": [
        "/contact", "/nous-contacter", "/contactez-nous",
        "/fr/contact", "/fr/nous-contacter",
        "/a-propos", "/fr/a-propos",
        "/notre-equipe", "/fr/notre-equipe",
    ],
    "ar": [
        "/contact", "/ar/contact",
        "/about", "/ar/about",
        "/team", "/ar/team",
    ],
    "ja": [
        "/contact", "/お問い合わせ", "/お問い合わせ/",
        "/about", "/会社概要", "/会社案内",
        "/access", "/アクセス",
    ],
    "es": [
        "/contacto", "/contacto/", "/CONTACTO",
        "/sobre-nosotros", "/quienes-somos",
        "/equipo", "/nuestro-equipo",
    ],
    "de": [
        "/kontakt", "/kontakt/", "/KONTAKT",
        "/ueber-uns", "/uber-uns",
        "/team", "/unser-team",
    ],
    "pt": [
        "/contato", "/contato/",
        "/sobre", "/sobre-nos",
        "/equipe", "/nossa-equipe",
    ],
    "it": [
        "/contatti", "/contatti/",
        "/chi-siamo", "/su-di-noi",
        "/team", "/nostro-team",
    ],
    "tr": [
        "/iletisim", "/iletisim/",
        "/hakkimizda", "/biz-kimiz",
        "/ekibimiz",
    ],
    "ru": [
        "/contacts", "/contacts/",
        "/about", "/about/",
        "/team", "/team/",
    ],
    "zh": [
        "/contact", "/联系我们", "/关于我们",
        "/about", "/about-us", "/team",
    ],
    "ko": [
        "/contact", "/contact-us",
        "/about", "/about-us",
        "/team", "/our-team",
    ],
}


# =============================================================================
# MAIN FUNCTIONS
# =============================================================================

def detect_country(location: str) -> str:
    """Detect country from location string."""
    loc_lower = location.lower().strip()

    for key, langs in COUNTRY_LANGUAGES.items():
        if key in loc_lower or loc_lower in key:
            return key

    return ""


def get_languages_for_country(country: str) -> List[str]:
    """Get language priority list for a country."""
    country_lower = country.lower().strip()
    return COUNTRY_LANGUAGES.get(country_lower, ["en"])


def get_accept_language(country: str) -> str:
    """Get Accept-Language header for a country."""
    languages = get_languages_for_country(country)
    if languages:
        return ACCEPT_LANGUAGE_HEADERS.get(languages[0], "en-US,en;q=0.9")
    return "en-US,en;q=0.9"


def get_contact_paths_for_country(country: str) -> List[str]:
    """Get contact paths to crawl based on country."""
    languages = get_languages_for_country(country)
    paths = []

    for lang in languages:
        lang_paths = CONTACT_PATHS_BY_LANG.get(lang, [])
        paths.extend(lang_paths)

    # Always include English paths as fallback
    for path in CONTACT_PATHS_BY_LANG["en"]:
        if path not in paths:
            paths.append(path)

    return paths


def expand_query(query: str, country: str) -> List[str]:
    """
    Expand a query to all relevant languages for a country.

    User types "pharmacy" → returns ["pharmacy", "pharmacie", "صيدلية", "薬局"]
    User types "صيدلية" → detects it's Arabic → returns ["pharmacy", "pharmacie", "薬局"]
    """
    query_lower = query.lower().strip()

    # Step 1: Try direct match (user typed English)
    if query_lower in BUSINESS_TYPES:
        entry = BUSINESS_TYPES[query_lower]
        languages = get_languages_for_country(country)
        expanded = []
        for lang in languages:
            if lang in entry:
                expanded.extend(entry[lang])
        if "en" in entry:
            for w in entry["en"]:
                if w not in expanded:
                    expanded.append(w)
        return list(dict.fromkeys(expanded))

    # Step 2: Try reverse lookup (user typed in any language)
    if query_lower in REVERSE_MAP:
        eng_type = REVERSE_MAP[query_lower]
        return expand_query(eng_type, country)

    # Step 3: Try partial match
    for key, eng_type in REVERSE_MAP.items():
        if query_lower in key or key in query_lower:
            return expand_query(eng_type, country)

    # Step 4: Return as-is (unknown term)
    return [query]


def get_osm_amenity(query: str) -> str:
    """Get the OSM amenity type for a query."""
    query_lower = query.lower().strip()

    if query_lower in BUSINESS_TYPES:
        entry = BUSINESS_TYPES[query_lower]
        return entry.get("osm_amenity") or entry.get("osm_shop") or entry.get("osm_tourism") or query_lower

    if query_lower in REVERSE_MAP:
        eng_type = REVERSE_MAP[query_lower]
        if eng_type in BUSINESS_TYPES:
            entry = BUSINESS_TYPES[eng_type]
            return entry.get("osm_amenity") or entry.get("osm_shop") or entry.get("osm_tourism") or query_lower

    return query_lower


def get_all_languages_for_query(query: str) -> List[str]:
    """Get ALL language translations for a query (for maximum coverage)."""
    query_lower = query.lower().strip()

    if query_lower in BUSINESS_TYPES:
        all_words = []
        for lang_words in BUSINESS_TYPES[query_lower].values():
            if isinstance(lang_words, list):
                all_words.extend(lang_words)
        return list(dict.fromkeys(all_words))

    if query_lower in REVERSE_MAP:
        eng_type = REVERSE_MAP[query_lower]
        return get_all_languages_for_query(eng_type)

    return [query]


# =============================================================================
# OSM TAG LOOKUP TABLE
# Maps OSM tag values to their (key, value) pairs for fuzzy matching
# =============================================================================
ALL_OSM_VALUES = {
    # amenity values
    "restaurant": ("amenity", "restaurant"),
    "cafe": ("amenity", "cafe"),
    "bar": ("amenity", "bar"),
    "pub": ("amenity", "pub"),
    "fast_food": ("amenity", "fast_food"),
    "pharmacy": ("amenity", "pharmacy"),
    "dentist": ("amenity", "dentist"),
    "doctors": ("amenity", "doctors"),
    "clinic": ("amenity", "clinic"),
    "hospital": ("amenity", "hospital"),
    "bank": ("amenity", "bank"),
    "atm": ("amenity", "atm"),
    "school": ("amenity", "school"),
    "university": ("amenity", "university"),
    "college": ("amenity", "college"),
    "kindergarten": ("amenity", "kindergarten"),
    "library": ("amenity", "library"),
    "fuel": ("amenity", "fuel"),
    "parking": ("amenity", "parking"),
    "taxi": ("amenity", "taxi"),
    "car_rental": ("amenity", "car_rental"),
    "car_wash": ("amenity", "car_wash"),
    "car_repair": ("amenity", "car_repair"),
    "post_office": ("amenity", "post_office"),
    "veterinary": ("amenity", "veterinary"),
    "optician": ("amenity", "optician"),
    "hairdresser": ("amenity", "hairdresser"),
    "bakery": ("amenity", "bakery"),
    "supermarket": ("amenity", "supermarket"),
    "convenience": ("amenity", "convenience"),
    "gym": ("amenity", "gym"),
    "spa": ("amenity", "spa"),
    "coworking": ("amenity", "coworking"),
    "bureau_de_change": ("amenity", "bureau_de_change"),
    "ice_cream": ("amenity", "ice_cream"),
    "food_court": ("amenity", "food_court"),
    "community_centre": ("amenity", "community_centre"),
    "social_centre": ("amenity", "social_centre"),
    "nightclub": ("amenity", "nightclub"),
    "cinema": ("amenity", "cinema"),
    "theatre": ("amenity", "theatre"),
    "arts_centre": ("amenity", "arts_centre"),
    "marketplace": ("amenity", "marketplace"),
    # shop values
    "chemist": ("shop", "chemist"),
    "beauty": ("shop", "beauty"),
    "fashion": ("shop", "fashion"),
    "clothes": ("shop", "clothes"),
    "shoes": ("shop", "shoes"),
    "jewelry": ("shop", "jewelry"),
    "jewellery": ("shop", "jewelry"),
    "watchmaker": ("shop", "watchmaker"),
    "electronics": ("shop", "electronics"),
    "computer": ("shop", "computer"),
    "mobile_phone": ("shop", "mobile_phone"),
    "furniture": ("shop", "furniture"),
    "hardware": ("shop", "hardware"),
    "doityourself": ("shop", "doityourself"),
    "garden_centre": ("shop", "garden_centre"),
    "florist": ("shop", "florist"),
    "books": ("shop", "books"),
    "stationery": ("shop", "stationery"),
    "gift": ("shop", "gift"),
    "sports": ("shop", "sports"),
    "outdoor": ("shop", "outdoor"),
    "pet": ("shop", "pet"),
    "car": ("shop", "car"),
    "bicycle": ("shop", "bicycle"),
    "motorcycle": ("shop", "motorcycle"),
    "department_store": ("shop", "department_store"),
    "mall": ("shop", "mall"),
    "kiosk": ("shop", "kiosk"),
    "greengrocer": ("shop", "greengrocer"),
    "butcher": ("shop", "butcher"),
    "deli": ("shop", "deli"),
    "seafood": ("shop", "seafood"),
    "wine": ("shop", "wine"),
    "alcohol": ("shop", "alcohol"),
    "health_food": ("shop", "health_food"),
    "medical_supply": ("shop", "medical_supply"),
    "cosmetics": ("shop", "cosmetics"),
    "perfumery": ("shop", "perfumery"),
    "bag": ("shop", "bag"),
    "accessories": ("shop", "accessories"),
    "tyres": ("shop", "tyres"),
    "travel_agency": ("shop", "travel_agency"),
    "laundry": ("shop", "laundry"),
    "tailor": ("shop", "tailor"),
    "shoemaker": ("shop", "shoemaker"),
    "carpet": ("shop", "carpet"),
    "curtain": ("shop", "curtain"),
    "bed": ("shop", "bed"),
    "kitchen": ("shop", "kitchen"),
    "bathroom": ("shop", "bathroom"),
    "lighting": ("shop", "lighting"),
    "paint": ("shop", "paint"),
    "paper": ("shop", "paper"),
    "tickets": ("shop", "tickets"),
    # tourism values
    "hotel": ("tourism", "hotel"),
    "motel": ("tourism", "motel"),
    "hostel": ("tourism", "hostel"),
    "guest_house": ("tourism", "guest_house"),
    "camp_site": ("tourism", "camp_site"),
    "caravan_site": ("tourism", "caravan_site"),
    "museum": ("tourism", "museum"),
    "attraction": ("tourism", "attraction"),
    "viewpoint": ("tourism", "viewpoint"),
    "artwork": ("tourism", "artwork"),
    "information": ("tourism", "information"),
    # healthcare values
    "healthcare": ("healthcare", "clinic"),
    "laboratory": ("healthcare", "laboratory"),
    "optometrist": ("healthcare", "optometrist"),
    # craft values
    "carpenter": ("craft", "carpenter"),
    "plumber": ("craft", "plumber"),
    "electrician": ("craft", "electrician"),
    "painter": ("craft", "painter"),
    "photographer": ("craft", "photographer"),
    "jeweller": ("craft", "jeweller"),
    "key_cutter": ("craft", "key_cutter"),
    "locksmith": ("craft", "locksmith"),
    "signmaker": ("craft", "signmaker"),
    # leisure values
    "fitness_centre": ("leisure", "fitness_centre"),
    "sports_centre": ("leisure", "sports_centre"),
    "swimming_pool": ("leisure", "swimming_pool"),
    "bowling_alley": ("leisure", "bowling_alley"),
    "amusement_arcade": ("leisure", "amusement_arcade"),
    # office values
    "lawyer": ("office", "lawyer"),
    "accountant": ("office", "accountant"),
    "insurance": ("office", "insurance"),
    "estate_agent": ("office", "estate_agent"),
    "company": ("office", "company"),
    # building values
    "office": ("building", "office"),
    "retail": ("building", "retail"),
    "industrial": ("building", "industrial"),
    "warehouse": ("building", "warehouse"),
}


def fuzzy_match_osm_tag(keyword: str) -> Optional[Tuple[str, str]]:
    """Fuzzy match a keyword to an OSM tag."""
    keyword_lower = keyword.lower().strip()

    # Exact match first
    if keyword_lower in ALL_OSM_VALUES:
        return ALL_OSM_VALUES[keyword_lower]

    # Fuzzy match
    all_values = list(ALL_OSM_VALUES.keys())
    matches = difflib.get_close_matches(keyword_lower, all_values, n=1, cutoff=0.6)

    if matches:
        return ALL_OSM_VALUES[matches[0]]

    return None


def get_osm_tags(query: str) -> List[Tuple[str, str]]:
    """
    Get ALL OSM tag pairs for ANY user keyword.

    Returns: [(tag_key, tag_value), ...]
    Example: "pharmacy" -> [("amenity", "pharmacy"), ("shop", "chemist")]
    Example: "boulangerie" -> [("shop", "bakery")]
    Example: "teppanyaki" -> [] (empty, use name search fallback)
    """
    query_lower = query.lower().strip()

    # Layer 1: Exact match in BUSINESS_TYPES
    if query_lower in BUSINESS_TYPES:
        tags = []
        bt = BUSINESS_TYPES[query_lower]
        for key in ["osm_amenity", "osm_shop", "osm_tourism", "osm_healthcare",
                     "osm_leisure", "osm_craft", "osm_office"]:
            if key in bt:
                tag_key = key.replace("osm_", "")
                tags.append((tag_key, bt[key]))
        return tags

    # Layer 2: Reverse lookup (non-English to English)
    if query_lower in REVERSE_MAP:
        eng_type = REVERSE_MAP[query_lower]
        return get_osm_tags(eng_type)

    # Layer 3: Fuzzy match against OSM tag values
    match = fuzzy_match_osm_tag(query_lower)
    if match:
        return [match]

    # Layer 4: No tag match - will use name search
    return []


def get_osm_tags_for_bbox(query: str, bbox: Tuple) -> str:
    """Build Overpass QL filter string for all tag types in a bbox."""
    tags = get_osm_tags(query)
    filter_lines = []

    for tag_key, tag_value in tags:
        filter_lines.append(f'nwr["{tag_key}"="{tag_value}"]({bbox[0]},{bbox[1]},{bbox[2]},{bbox[3]});')

    # Always add name search as fallback
    escaped_query = query.replace('"', '\\"')
    filter_lines.append(f'nwr["name"~"{escaped_query}",i]({bbox[0]},{bbox[1]},{bbox[2]},{bbox[3]});')

    return "\n".join(filter_lines)
